package gander

import (
	"log"
	"testing"
)

func logErr(err error) {
	if err != nil {
		log.Println(err)
	}
}

var names = []string{"Aad", "Aadam", "Aadje", "Ådne", "Aadu", "af", "Aafke", "Aafke", "Aafkea", "Aafko", "Aage", "Åge", "Aagje", "Aagot", "Ågot", "Aagoth", "Ågoth", "Åke", "Aalbert", "Aalderich", "Aalderk", "Aaldrik", "Aale", "Aaliyah", "Aalke", "Aalt", "Aaltien", "Aaltinus", "Aaltje", "Aaltsje", "Aamir", "ant", "Aapeli", "Aapo", "Aappo", "Aard", "Aare", "Aarent", "Aarjan", "Aarne", "Aarni", "Aarno", "Aarnoud", "Aarnout", "Aaro", "Aaron", "Aarón", "Aarre", "Aarron", "Aart", "Aarti", "Åsa", "Aase", "Åse", "Åsgeir", "Aashild", "Åshild", "Åslaug", "Åsmund", "Åste", "Aat", "Aatami", "Aatos", "Aatto", "Aatu", "Aave", "Aavo", "Ab", "Abad", "Abagail", "Abai", "Abas", "Abay", "Abaz", "Abbas", "Abbe", "Abbe", "Abbey", "Abbie", "Abbigail", "Abbo", "Abbondanza", "Abbondanzio", "Abbondio", "Abby", "Abd", "Abdal", "Abdalla", "Abdallah", "Abdal", "Abdel", "Abdel", "Abdel", "Abdel", "Abdel", "Abdel", "Abdel", "Abdel", "Abdel", "Abdel", "Abdelilah", "Abdel", "Abdel", "Abdellah", "Abdel", "Abdel", "Abdel", "Abder", "Abder", "Abder", "Abder", "Abdeslam", "Abdi", "Abdija", "Abdo", "Abdol", "Abdol", "Abdol", "Abdon", "Abdorassoul", "Abdou", "Abdoul", "Abdu", "Abdülhalim", "Abdülhamid", "Abdülkadir", "Abdülkerim", "Abdüllatif", "Abdülsamet", "Abduh", "Abdul", "Abdulah", "Abdul", "Abdul", "Abdul", "Abdul", "Abdulbaki", "Abdul", "Abdulcabbar", "Abdul", "Abdul", "Abdul", "Abdulhakim", "Abdul", "Abdul", "Abdülhalim", "Abdul", "Abdülhamid", "Abdul", "Abdulilah", "Abdul", "Abdulkader", "Abdul", "Abdulkadir", "Abdul", "Abdülkadir", "Abdulkadyr", "Abdul", "Abdul", "Abdulkerim", "Abdülkerim", "Abdul", "Abdulla", "Abdullah", "Abdul", "Abdüllatif", "Abdul", "Abdulmalik", "Abdulmedjit", "Abdul", "Abdul", "Abdul", "Abdul", "Abdul", "Abdul", "Abdulsamet", "Abdülsamet", "Abdul", "Abdul", "Abdurahman", "Abdurrahim", "Abdur", "Abdurrahman", "Abdur", "Abdyl", "Abe", "Abe", "Abed", "Abeda", "Abedin", "Abeer", "Abel", "Ábel", "Abelardo", "Abele", "Abelia", "Abeline", "Abelio", "Abelius", "Abelle", "Abha", "Abhay", "Abhilasha", "Abid", "Abida", "Abidin", "Abigaël", "Abigaëlle", "Abigail", "Abigale", "Abigayle", "Abilia", "Abília", "Abilio", "Abílio", "Abir", "Abla", "Ablah", "Abner", "Abraão", "Abraham", "Abram", "Abramina", "Abramo", "Abrar", "Abrytha", "Abu", "Abu", "Abubekir", "Abuzar", "Abuzer", "Aby", "Abygaël", "Abygaëlle", "Aca", "Acacio", "Acácio", "Accursia", "Accursio", "Achaz", "Achicam", "Achikam", "Achilina", "Achille", "Achilleas", "Achillefs", "Achim", "Achim", "Achiropita", "Achraf", "Acilino", "Acim", "Acke", "Acko", "Aco", "Aculina", "Acúrcio", "Ad", "Ada", "Ad", "Ad", "dair", "Adakras", "Adalbert", "Adalberta", "Adalberto", "Aðalbjörg", "Aðalbjörn", "Aðalbjörg", "Aðalbjörn", "Adalciza", "Adalet", "Aðalgeir", "Adalgira", "Adalgisa", "Adalgiso", "Aðalheiður", "Adalmiina", "Aðalsteinn", "Adam", "Ádám", "Adama", "dama", "Adamantia", "Adamantini", "Adamantios", "Adamira", "Adamo", "Adan", "Adán", "Adaniel", "Adão", "Adar", "Adarsh", "Adda", "Adda", "Addi", "Addie", "Addie", "Addison", "Addolorata", "Addolorato", "Addy", "Addy", "Addy", "Ade", "Adea", "Adeele", "Adel", "del", "Adela", "Adéla", "Adelaida", "Adelaide", "Adélaïde", "Adelaïde", "Adelaido", "Adelajde", "Adelbert", "Adelchi", "Adele", "Adelė", "Adèle", "Adéle", "Adelfa", "Adelfo", "Adelfried", "Adelgund", "Adelgunde", "Adelhard", "Adelheid", "Adelheide", "Adelia", "Adélia", "Adélie", "Adelin", "Adelina", "Adelinda", "Adelinde", "Adelindo", "Adeline", "Adelino", "Adelio", "Adélio", "Adelisa", "Adeliya", "Adell", "Adell", "Adella", "Adelle", "Adelma", "Adelmar", "Adelmina", "Adelmino", "Adelmira", "Adelmo", "Adelo", "Adelphine", "Adeltraud", "Adeltraut", "Adeluţa", "Adelya", "Adelyne", "Adem", "Ademar", "Ademara", "Ademaro", "Aden", "Adeodata", "Adeodato", "Aderita", "Aderito", "Adérito", "Adham", "Adhémar", "Adhurim", "Adi", "Adi", "Adi", "Adi", "Adib", "Adiba", "Adil", "Adila", "Adilbek", "Adile", "Adilia", "Adília", "Adilkhan", "Adin", "Adina", "Adinda", "Adine", "Adinel", "Adino", "Adir", "Adis", "Adisa", "Aditi", "Aditya", "Adiya", "Adje", "Adjuto", "Admeto", "Admir", "Admira", "Admirim", "Adnan", "Adnana", "Adnand", "Ådne", "Ado", "Adolf", "Adolfa", "Adolfas", "Adolfina", "Adolfine", "Adolfo", "Ādolfs", "Adolina", "Adolph", "Adolphe", "Adolphine", "Adolphus", "Adomas", "Adone", "Adonis", "Adoración", "Adoram", "Adorata", "Adorján", "Adorna", "Adorno", "Adosinda", "Adosinha", "Adrasto", "Adri", "Adria", "Adriaan", "Adrian", "drian", "Adrián", "Adriana", "Adriane", "Adrianna", "Adrianne", "Adriano", "Adriāns", "Adrianus", "Adrião", "Adriatik", "Adrie", "Adriëlle", "Adrien", "Adriena", "Adrienn", "Adrienne", "Adriënne", "Adrijan", "Adrijana", "Adrio", "Ädu", "Adua", "Aduo", "Advija", "dy", "Ae", "Aedal", "Aedin", "Ädu", "Ägidius", "Ægir", "Aeihso", "Aeilt", "Aelbert", "Aelita", "Älke", "Aeneas", "Aengus", "Ännchen", "Aenne", "Änne", "Aerend", "Aernout", "Aeron", "Aeronwen", "Aeronwy", "Aert", "Æsa", "Ævar", "Ævarr", "Ae", "Afa", "Afaf", "Afag", "Afanasie", "Afanasii", "Afanasijs", "Afaq", "fat", "Afelien", "Aferdita", "Afërdita", "Afet", "Affie", "Afgan", "Afia", "Afie", "Afif", "Afifa", "Afifah", "Afiya", "fke", "Afonso", "Afra", "África", "Afrim", "Afro", "Afrodita", "Afroditi", "Afsaneh", "Afsar", "Afşar", "Afschin", "Afshin", "Aftab", "Aftandil", "Aftina", "Aftinia", "Afzal", "Aga", "Aga", "Agaat", "Agaath", "Agafia", "Agah", "Agan", "Agapi", "Agapia", "Agapios", "Agapita", "Agapito", "Agata", "Agáta", "Agate", "Agatha", "Agathe", "Agathi", "Agatho", "Agatia", "Agatina", "Agatino", "Agazio", "Agda", "Age", "Åge", "Ageet", "Ageeth", "Agenore", "Ager", "Agesilao", "Agetina", "Agge", "Aggeo", "Aggie", "Agha", "Aghasi", "Aghavni", "Aghvan", "Ági", "Ági", "Agide", "Ägidius", "Agil", "Agilbert", "Agilmar", "Agim", "Ægir", "Agis", "Agisilaos", "Agita", "Agla", "Aglaé", "Aglaea", "Aglaée", "Aglaia", "Aglaja", "Aglaya", "Agle", "Agna", "Agnar", "Agne", "Agne", "Agnė", "Agnela", "Agnella", "Agnello", "Agnelo", "Agner", "Agnes", "Ágnes", "Agnès", "Agnesa", "Agnese", "Agneta", "Agnete", "Agnetha", "Agnethe", "Agneza", "Agni", "Agnieška", "Agnieška", "Agnieška", "Agnieszka", "Agnietė", "Agnija", "Agnis", "Agnita", "Ago", "Agon", "Agora", "Agoritsa", "Agostina", "Agostiña", "Agostiña", "Agostinho", "Agostino", "Ágoston", "Ågot", "Agota", "Ágota", "Ågoth", "Agra", "Agripina", "Agrippina", "Agrippino", "Agris", "Agrita", "Agron", "Agshin", "Agu", "Águeda", "Aguinaldo", "Agunde", "Agurne", "Agurtzane", "Ágúst", "Ágústa", "Agusti", "Agustin", "Agustín", "Agustina", "Ágústína", "Ah", "Aharon", "Aherine", "Ahilan", "Ahile", "Ahlam", "Ahlerich", "hlke", "Ahlrich", "Ahlrike", "Ahmad", "Ahmed", "Ahmet", "Ahmo", "Ahrend", "Ahsen", "Ahti", "Ahto", "Ahu", "Ahuva", "Ahuvah", "Ai", "Ai", "Aia", "Aiace", "Aibek", "Ai", "Ai", "Aicha", "Ai", "Ai", "Aicke", "Aida", "Aïda", "Aidan", "Aidana", "Aidar", "Aidas", "Aide", "Aideen", "Aidel", "Aiden", "Ai", "Aido", "Ai", "Aiert", "Ai", "Ai", "Ai", "Ai", "Aiga", "Aigar", "Aigars", "Aigerim", "Aigris", "Aigul", "Ai", "Ai", "Ai", "Ai", "Aija", "Ai", "Ai", "Ai", "Ai", "Aikaterini", "ike", "Aiki", "Aiko", "Aiko", "Ai", "Aila", "Ai", "ilbhe", "Aile", "ilean", "Aileen", "Ailert", "Aili", "ili", "Ai", "Ai", "Ai", "Ailidh", "Ailie", "Ailin", "Ai", "Ailín", "Ai", "Ailis", "Ailís", "Ailish", "Ailsa", "Ailt", "Aima", "imable", "Aiman", "Aiman", "Aimantas", "Aimar", "Aime", "Aimé", "Aimee", "Aimée", "Ai", "Aimeric", "Aimery", "Aimi", "Aimie", "Aimilia", "Aimilios", "Ai", "Ai", "Aimo", "Aimur", "Aimy", "Ain", "Aina", "Ainagul", "Ainar", "Ainara", "Ainars", "Ainārs", "Ainash", "Aindrias", "Aindriú", "ine", "Áine", "Aingeru", "Ainhoa", "Aini", "Ainikki", "Ai", "Ainis", "Aino", "Aino", "Ainoriitta", "insley", "Ainsley", "Ainsworth", "Aintzane", "Ainur", "Ainura", "Ai", "Ai", "Ai", "Ai", "Aira", "Aire", "Aires", "Airete", "Airi", "Airidas", "Airina", "Airo", "Ai", "Ai", "Aiša", "Aischa", "Aiša", "Aisha", "Aiša", "Aishah", "Aishe", "Aishling", "Aislin", "Aisling", "Aislinn", "Aisma", "Aiso", "Aita", "Aitan", "Aitana", "Aiten", "Ai", "Aitor", "Aitzol", "Aiva", "Aivar", "Aivaras", "Aivars", "Aive", "Aivi", "Aivils", "Aivis", "Aivo", "Ai", "Ai", "Ai", "Ai", "Ai", "Ai", "Ai", "Ai", "Ai", "Aiyana", "Ai", "Ai", "Ai", "Ai", "Ai", "Aize", "Aizhan", "Ai", "Ai", "Ai", "Ai", "Ai", "Aizo", "Aja", "Ajay", "Ajaz", "Ajda", "Ajdin", "Ajdina", "Ajet", "Ajeta", "Ajete", "Ajiša", "Ajiša", "Ajiša", "jit", "Ajka", "Ajkun", "Ajkune", "Ajla", "Ajmal", "Ajmer", "Ajrie", "Ajša", "Ajša", "Ajša", "Ajshe", "Ajten", "Ajtene", "Ajub", "Akaki", "Akan", "Akane", "Akari", "Akash", "Akbar", "Akbota", "Akçay", "Ake", "Åke", "Akeem", "Akemi", "Aketza", "Akgül", "Akgül", "Akhila", "Akhtar", "Aki", "Aki", "Áki", "Akiba", "Akif", "Akife", "Akifumi", "Akiharu", "Akihiko", "Akihiro", "Akihisa", "Akihito", "Akikazu", "Akiko", "Akil", "Akila", "Akim", "Akimasa", "Akimitsu", "Akın", "Akina", "Akindynos", "Akino", "Akinobu", "Akinori", "Akio", "kira", "kito", "Akitomo", "Akitoshi", "Akiva", "Akiyo", "Akiyoshi", "Akke", "Akkie", "Akmal", "Akmaral", "Akmini", "Ákos", "Akper", "Akram", "Akrivi", "Akrom", "Aksana", "Aksel", "Akseli", "Aku", "Akylbek", "Al", "l", "Ala", "la", "laa", "Alaaddin", "Alaattin", "Aladár", "Aladdin", "Aladina", "Aladino", "Alaeddine", "Alaettin", "Alaga", "Alain", "Alaina", "Alaïs", "Alaitz", "Alajos", "Alak", "Alakananda", "Al", "Al", "Alam", "Alamanno", "Alamgir", "Alan", "Alana", "Alanah", "Alane", "Alanis", "Alanna", "Alannah", "Alar", "Alari", "Alaric", "Alarich", "Alarico", "Alarik", "Alasdair", "Alastair", "Alaster", "Alayna", "layne", "Alazdin", "Alazne", "Alba", "Albain", "Alban", "Albana", "Albane", "Albanie", "Albanne", "Albano", "Albena", "Alber", "Alberdina", "Alberdine", "Albéric", "Alberica", "Alberico", "Albert", "Alberta", "Albertas", "Albertdine", "Alberte", "Albertha", "Alberthe", "Albertien", "Albertina", "Albertine", "Albertino", "Albertje", "Alberto", "Alberts", "Albertus", "Albi", "Albi", "Albin", "Albina", "Albīna", "Albína", "Albinas", "Albinca", "Albine", "Albino", "Albinus", "Albion", "Albo", "Albrecht", "Albulena", "Alby", "Alby", "Alcea", "Alceo", "Alceste", "Alceu", "Alcide", "Alcides", "Alcídia", "Alcina", "Alcinda", "Alcindo", "Alcínio", "Alcino", "Alco", "Alda", "Aldas", "Aldegonda", "Alden", "Aldéric", "Alderico", "Aldesina", "Aldesino", "Aldi", "Aldijana", "Aldin", "Aldina", "Aldine", "Aldino", "Aldis", "Aldís", "Aldo", "Aldobrando", "Aldona", "Aldonija", "Aldónio", "Aldonis", "Aldor", "Aldous", "Aldric", "Aldrich", "Aldrik", "Alduina", "Alduino", "Aldwin", "Aldwyn", "Ale", "Alė"}

func TestGanderIterative(t *testing.T) {
	var males int
	var females int
	var total int
	for _, n := range names {
		g, err := CheckGender(n)
		total++
		if err == nil {
			if g.Gender == "f" {
				females++
			} else if g.Gender == "m" {
				males++
			}
		}
	}
	t.Logf("In %d we found %d females and %d males", total, females, males)
	t.Logf("Not found = %d", total-(females+males))
}

func TestAllLoadedNames(t *testing.T) {
	var males int
	var females int
	for _, n := range NGData {
		g, err := CheckGender(n.Name)
		if err == nil {
			if g.Gender == "f" {
				females++
			} else {
				males++
			}
		}
	}
	t.Logf("In %d we found %d females and %d males", len(NGData), females, males)
}

func TestGanderSingles(t *testing.T) {
	r, err := CheckGender("Aad")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aadam")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aadje")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ådne")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aadu")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("af")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aafke")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aafke")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aafkea")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aafko")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aage")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Åge")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aagje")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aagot")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ågot")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aagoth")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ågoth")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Åke")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aalbert")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aalderich")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aalderk")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aaldrik")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aale")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aaliyah")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aalke")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aalt")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aaltien")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aaltinus")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aaltje")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aaltsje")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aamir")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("ant")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aapeli")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aapo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aappo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aard")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aare")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aarent")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aarjan")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aarne")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aarni")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aarno")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aarnoud")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aarnout")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aaro")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aaron")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aarón")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aarre")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aarron")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aart")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aarti")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Åsa")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aase")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Åse")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Åsgeir")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aashild")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Åshild")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Åslaug")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Åsmund")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Åste")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aat")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aatami")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aatos")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aatto")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aatu")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aave")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aavo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ab")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abad")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abagail")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abas")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abay")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abaz")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abbas")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abbe")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abbe")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abbey")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abbie")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abbigail")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abbo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abbondanza")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abbondanzio")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abbondio")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abby")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abd")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdal")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdalla")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdallah")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdal")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdel")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdel")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdel")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdel")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdel")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdel")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdel")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdel")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdel")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdel")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdelilah")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdel")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdel")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdellah")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdel")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdel")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdel")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abder")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abder")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abder")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abder")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdeslam")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdi")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdija")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdol")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdol")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdol")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdon")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdorassoul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdou")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdoul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdu")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdülhalim")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdülhamid")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdülkadir")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdülkerim")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdüllatif")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdülsamet")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abduh")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdulah")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdulbaki")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdulcabbar")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdulhakim")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdülhalim")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdülhamid")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdulilah")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdulkader")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdulkadir")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdülkadir")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdulkadyr")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdulkerim")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdülkerim")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdulla")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdullah")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdüllatif")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdulmalik")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdulmedjit")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdulsamet")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdülsamet")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdurahman")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdurrahim")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdur")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdurrahman")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdur")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abdyl")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abe")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abe")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abed")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abeda")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abedin")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abeer")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abel")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ábel")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abelardo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abele")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abelia")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abeline")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abelio")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abelius")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abelle")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abha")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abhay")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abhilasha")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abid")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abida")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abidin")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abigaël")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abigaëlle")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abigail")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abigale")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abigayle")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abilia")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abília")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abilio")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abílio")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abir")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abla")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ablah")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abner")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abraão")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abraham")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abram")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abramina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abramo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abrar")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abrytha")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abu")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abu")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abubekir")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abuzar")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abuzer")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aby")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abygaël")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Abygaëlle")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aca")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Acacio")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Acácio")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Accursia")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Accursio")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Achaz")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Achicam")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Achikam")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Achilina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Achille")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Achilleas")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Achillefs")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Achim")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Achim")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Achiropita")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Achraf")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Acilino")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Acim")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Acke")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Acko")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aco")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aculina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Acúrcio")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ad")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ada")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ad")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ad")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("dair")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adakras")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adalbert")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adalberta")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adalberto")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aðalbjörg")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aðalbjörn")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aðalbjörg")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aðalbjörn")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adalciza")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adalet")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aðalgeir")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adalgira")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adalgisa")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adalgiso")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aðalheiður")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adalmiina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aðalsteinn")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adam")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ádám")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adama")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("dama")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adamantia")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adamantini")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adamantios")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adamira")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adamo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adan")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adán")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adaniel")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adão")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adar")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adarsh")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adda")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adda")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Addi")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Addie")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Addie")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Addison")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Addolorata")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Addolorato")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Addy")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Addy")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Addy")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ade")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adea")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adeele")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adel")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("del")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adela")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adéla")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelaida")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelaide")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adélaïde")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelaïde")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelaido")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelajde")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelbert")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelchi")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adele")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelė")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adèle")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adéle")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelfa")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelfo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelfried")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelgund")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelgunde")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelhard")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelheid")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelheide")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelia")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adélia")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adélie")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelin")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelinda")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelinde")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelindo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adeline")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelino")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelio")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adélio")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelisa")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adeliya")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adell")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adell")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adella")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelle")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelma")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelmar")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelmina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelmino")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelmira")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelmo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelphine")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adeltraud")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adeltraut")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adeluţa")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelya")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adelyne")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adem")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ademar")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ademara")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ademaro")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aden")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adeodata")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adeodato")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aderita")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aderito")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adérito")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adham")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adhémar")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adhurim")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adi")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adi")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adi")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adi")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adib")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adiba")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adil")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adila")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adilbek")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adile")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adilia")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adília")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adilkhan")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adin")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adinda")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adine")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adinel")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adino")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adir")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adis")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adisa")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aditi")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aditya")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adiya")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adje")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adjuto")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Admeto")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Admir")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Admira")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Admirim")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adnan")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adnana")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adnand")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ådne")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ado")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adolf")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adolfa")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adolfas")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adolfina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adolfine")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adolfo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ādolfs")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adolina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adolph")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adolphe")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adolphine")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adolphus")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adomas")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adone")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adonis")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adoración")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adoram")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adorata")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adorján")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adorna")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adorno")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adosinda")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adosinha")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adrasto")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adri")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adria")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adriaan")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adrian")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("drian")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adrián")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adriana")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adriane")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adrianna")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adrianne")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adriano")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adriāns")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adrianus")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adrião")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adriatik")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adrie")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adriëlle")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adrien")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adriena")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adrienn")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adrienne")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adriënne")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adrijan")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adrijana")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adrio")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ädu")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Adua")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aduo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Advija")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("dy")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ae")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aedal")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aedin")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ädu")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ägidius")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ægir")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aeihso")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aeilt")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aelbert")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aelita")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Älke")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aeneas")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aengus")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ännchen")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aenne")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Änne")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aerend")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aernout")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aeron")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aeronwen")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aeronwy")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aert")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Æsa")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ævar")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ævarr")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ae")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afa")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afaf")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afag")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afanasie")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afanasii")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afanasijs")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afaq")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("fat")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afelien")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aferdita")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afërdita")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afet")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Affie")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afgan")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afia")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afie")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afif")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afifa")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afifah")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afiya")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("fke")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afonso")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afra")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("África")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afrim")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afro")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afrodita")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afroditi")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afsaneh")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afsar")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afşar")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afschin")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afshin")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aftab")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aftandil")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aftina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aftinia")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Afzal")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aga")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aga")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agaat")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agaath")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agafia")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agah")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agan")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agapi")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agapia")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agapios")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agapita")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agapito")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agata")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agáta")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agate")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agatha")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agathe")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agathi")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agatho")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agatia")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agatina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agatino")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agazio")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agda")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Age")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Åge")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ageet")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ageeth")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agenore")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ager")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agesilao")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agetina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agge")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aggeo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aggie")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agha")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aghasi")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aghavni")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aghvan")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ági")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ági")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agide")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ägidius")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agil")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agilbert")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agilmar")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agim")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ægir")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agis")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agisilaos")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agita")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agla")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aglaé")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aglaea")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aglaée")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aglaia")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aglaja")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aglaya")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agle")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agna")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agnar")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agne")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agne")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agnė")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agnela")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agnella")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agnello")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agnelo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agner")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agnes")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ágnes")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agnès")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agnesa")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agnese")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agneta")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agnete")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agnetha")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agnethe")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agneza")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agni")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agnieška")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agnieška")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agnieška")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agnieszka")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agnietė")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agnija")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agnis")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agnita")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ago")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agon")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agora")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agoritsa")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agostina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agostiña")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agostiña")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agostinho")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agostino")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ágoston")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ågot")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agota")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ágota")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ågoth")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agra")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agripina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agrippina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agrippino")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agris")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agrita")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agron")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agshin")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agu")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Águeda")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aguinaldo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agunde")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agurne")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agurtzane")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ágúst")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ágústa")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agusti")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agustin")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agustín")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Agustina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ágústína")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ah")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aharon")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aherine")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ahilan")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ahile")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ahlam")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ahlerich")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("hlke")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ahlrich")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ahlrike")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ahmad")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ahmed")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ahmet")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ahmo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ahrend")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ahsen")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ahti")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ahto")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ahu")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ahuva")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ahuvah")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aia")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aiace")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aibek")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aicha")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aicke")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aida")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aïda")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aidan")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aidana")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aidar")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aidas")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aide")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aideen")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aidel")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aiden")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aido")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aiert")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aiga")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aigar")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aigars")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aigerim")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aigris")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aigul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aija")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aikaterini")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("ike")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aiki")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aiko")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aiko")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aila")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("ilbhe")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aile")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("ilean")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aileen")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ailert")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aili")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("ili")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ailidh")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ailie")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ailin")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ailín")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ailis")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ailís")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ailish")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ailsa")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ailt")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aima")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("imable")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aiman")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aiman")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aimantas")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aimar")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aime")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aimé")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aimee")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aimée")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aimeric")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aimery")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aimi")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aimie")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aimilia")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aimilios")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aimo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aimur")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aimy")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ain")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ainagul")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ainar")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ainara")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ainars")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ainārs")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ainash")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aindrias")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aindriú")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("ine")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Áine")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aingeru")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ainhoa")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aini")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ainikki")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ainis")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aino")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aino")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ainoriitta")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("insley")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ainsley")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ainsworth")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aintzane")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ainur")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ainura")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aira")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aire")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aires")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Airete")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Airi")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Airidas")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Airina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Airo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aiša")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aischa")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aiša")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aisha")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aiša")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aishah")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aishe")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aishling")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aislin")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aisling")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aislinn")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aisma")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aiso")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aita")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aitan")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aitana")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aiten")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aitor")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aitzol")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aiva")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aivar")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aivaras")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aivars")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aive")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aivi")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aivils")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aivis")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aivo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aiyana")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aize")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aizhan")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ai")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aizo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aja")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ajay")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ajaz")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ajda")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ajdin")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ajdina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ajet")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ajeta")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ajete")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ajiša")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ajiša")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ajiša")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("jit")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ajka")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ajkun")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ajkune")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ajla")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ajmal")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ajmer")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ajrie")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ajša")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ajša")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ajša")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ajshe")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ajten")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ajtene")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ajub")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akaki")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akan")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akane")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akari")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akash")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akbar")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akbota")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akçay")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ake")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Åke")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akeem")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akemi")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aketza")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akgül")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akgül")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akhila")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akhtar")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aki")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aki")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Áki")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akiba")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akif")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akife")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akifumi")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akiharu")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akihiko")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akihiro")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akihisa")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akihito")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akikazu")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akiko")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akil")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akila")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akim")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akimasa")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akimitsu")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akın")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akindynos")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akino")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akinobu")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akinori")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akio")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("kira")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("kito")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akitomo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akitoshi")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akiva")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akiyo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akiyoshi")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akke")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akkie")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akmal")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akmaral")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akmini")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ákos")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akper")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akram")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akrivi")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akrom")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aksana")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aksel")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akseli")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aku")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Akylbek")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Al")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("l")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ala")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("la")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("laa")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alaaddin")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alaattin")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aladár")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aladdin")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aladina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aladino")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alaeddine")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alaettin")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alaga")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alain")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alaina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alaïs")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alaitz")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alajos")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alak")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alakananda")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Al")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Al")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alam")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alamanno")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alamgir")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alan")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alana")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alanah")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alane")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alanis")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alanna")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alannah")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alar")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alari")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alaric")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alarich")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alarico")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alarik")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alasdair")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alastair")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alaster")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alayna")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("layne")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alazdin")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alazne")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alba")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albain")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alban")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albana")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albane")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albanie")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albanne")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albano")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albena")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alber")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alberdina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alberdine")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albéric")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alberica")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alberico")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albert")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alberta")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albertas")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albertdine")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alberte")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albertha")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alberthe")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albertien")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albertina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albertine")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albertino")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albertje")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alberto")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alberts")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albertus")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albi")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albi")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albin")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albīna")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albína")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albinas")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albinca")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albine")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albino")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albinus")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albion")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albrecht")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Albulena")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alby")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alby")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alcea")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alceo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alceste")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alceu")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alcide")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alcides")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alcídia")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alcina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alcinda")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alcindo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alcínio")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alcino")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alco")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alda")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldas")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldegonda")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alden")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldéric")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alderico")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldesina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldesino")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldi")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldijana")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldin")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldine")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldino")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldis")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldís")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldo")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldobrando")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldona")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldonija")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldónio")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldonis")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldor")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldous")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldric")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldrich")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldrik")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alduina")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alduino")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldwin")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Aldwyn")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Ale")
	logErr(err)
	log.Println(r.Gender)
	r, err = CheckGender("Alė")
	logErr(err)
	log.Println(r.Gender)
}
